type Question {
    text: String!
    correct: Int!
    total: Int!
    lesson: Lesson!
}

type Lesson {
    title: String!
}

type Query {
  allLessons: [Lesson!]
  lessonByTitle(title: String!): Lesson!
  activeLessons(isActive: Boolean!): Lesson!
  questionsByQuestionText(text: String!): Question!
}